DROP TABLE DONNE_ACCES;
DROP TABLE PARRAINER;
DROP TABLE SPECIALISE;
DROP TABLE COHABITER;
DROP TABLE EST_PARENT;
DROP TABLE GENERE_CA;
DROP TABLE NOURRIT;
DROP TABLE TRAVAILLER;
DROP TABLE AFFECTER;

DROP TABLE SOINS;
DROP TABLE REPARATION;

DROP TABLE HISTORIQUE_EMPLOI;

DROP TABLE ANIMAL;
DROP TABLE BOUTIQUE;
DROP TABLE ENCLOS;

DROP TABLE VISITEUR;
DROP TABLE PRESTATAIRE;
DROP TABLE PRESTATION;
DROP TABLE NIVEAU;

DROP TABLE ZONE;

DROP TABLE PERSONNEL;

DROP TABLE ESPECE;